### PR TITLE
Delete the redundant code

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Delete the redundant code

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@xichengliudui , please fix the build error :)

**Comment by xichengliudui** [comment]
@k82cn ,Thank you for your reminding, I have changed, the 'key' is a local variable.

**Pull request merged**
