### PR TITLE
add queuejob to schedulercache

### LINKED ISSUE #58: schedulercache need notify controllers when being updated
Is this a BUG REPORT or FEATURE REQUEST?: FEATURE REQUEST

The queuejob controller need get notifications when Queue/QueueJob/Pods are being updated.

This could be implemented as a kind of shared informer and lister

/kind feature

### PR DESCRIPTION
**Pull request by hanghliu**
fixes #58

### CODE REVIEW

**Comment by jinzhejz** [comment]
@hanghliu need run `hack/verify-gofmt.sh` first and fix the code format issue.

**Comment by hanghliu** [comment]
Maybe we need hold merging this PR, 
1) Could "queue controller" and "queuejob controller" share "schedulecache"? How?
2) Different snapshot might be need for 2 controllers?

**Comment by k82cn** [comment]
@hanghliu , I'm thinking to build both controller into one binary; so they can share this cache and simplify the deployment of this project.

**Comment by hanghliu** [comment]
Ok. Thanks!

**Comment by jinzhejz** [comment]
@hanghliu 

Controller can get the Queue/QueueJob/Pod info from schedulecache by dump the snapshot,
however, currently schedulecache doesn't support to notice the controller automatically when Queue/QueueJob/Pod is updated.

The snapshot is enough for scheduler policy.
And I think schedulecache can support to notice QueueJob controller if needed.

**Comment by hanghliu** [comment]
I opened a feature request #58 to track schedulecache supporting to notice QueueJob controller.

**Comment by hanghliu** [comment]
@jinzhejz 
I am ok to close this PR.

**Comment by hanghliu** [comment]
I added queue/queuejob informer implementation to fix #58

**Review by jinzhejz — APPROVED** [review]
lgtm

**Pull request merged**
