### PR TITLE
Added Phase and Conditions to PodGroup.Status struct

### PR DESCRIPTION
**Pull request by Zyqsempai**
**What this PR does / why we need it**:

This PR add additional info fields for PodGroup.Status struct to get have more explicit info Status itself
**Which issue(s) this PR fixes**
https://github.com/kubernetes-sigs/kube-batch/issues/521

**Special notes for your reviewer**:
Two new fields: Phase and Conditions based on the same fields in the Pod.Status struct
**Release note**:
 `NONE`

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@k82cn Hi, can you provide some review please, notes, comments are welcome.

**Comment by k82cn** [comment]
Please use `make generate-code` to make CI happy. The other part LGTM.

**Comment by Zyqsempai** [comment]
@k82cn Done

**Pull request merged**
