### PR TITLE
Fix verify task

### LINKED ISSUE #969: Fix CI failed
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

xref: https://app.travis-ci.com/github/k82cn/kube-batch/builds/252710492

### PR DESCRIPTION
**Pull request by aivinog1**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #969 

**Special notes for your reviewer**: 
I've just passed the whole CI and updated libraries or files that diff. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
Maybe we need to update go version of CI in https://github.com/kubernetes-sigs/kube-batch/blob/master/.travis.yml

```
I0714 11:36:16.446] hack/verify-gofmt.sh
I0714 11:36:16.626] diff -u ./vendor.go.orig ./vendor.go
I0714 11:36:16.627] --- ./vendor.go.orig	2022-07-14 11:36:16.510474425 +0000
I0714 11:36:16.627] +++ ./vendor.go	2022-07-14 11:36:16.510474425 +0000
I0714 11:36:16.627] @@ -1,3 +1,4 @@
I0714 11:36:16.627] +//go:build vendor
I0714 11:36:16.627]  // +build vendor
I0714 11:36:16.627]  
I0714 11:36:16.627]  package main
W0714 11:36:16.633] make: *** [Makefile:16: verify] Error 1
```

**Comment by aivinog1** [comment]
Hey @k82cn. I think that the problem is a little bit deeper :) So, [this build](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kube-batch/970/pull-kube-batch-verify/1547545305862377472/) uses [this image](gcr.io/k8s-staging-test-infra/gcloud-in-go:v20220607-33951ed1ed) to build the code. You can see it [in the manifest](https://prow.k8s.io/prowjob?prowjob=0ef35540-0369-11ed-80ed-e206076a87d7). And in this image, the Go version is 1.17.11.
```shell
# go version
go version go1.17.11 linux/amd64
#
```
So, I think we should update this Go version of the whole app:
1. `go.mod`
2. `.travis.yml`
3. Maybe somewhere else too 😅

**Comment by aivinog1** [comment]
And I will try to fix it here, of course :)

**Comment by aivinog1** [comment]
@k82cn I've decided to not migrate with `go.mod` and replace the deprecated `go get ` stuff in the `hack/verify-golint.sh`. I think that we should create a separate issue about full migration to 1.17.

**Comment by k82cn** [comment]
> @k82cn I've decided to not migrate with `go.mod` and replace the deprecated `go get ` stuff in the `hack/verify-golint.sh`. I think that we should create a separate issue about full migration to 1.17.

that's ok to me :)

**Comment by aivinog1** [comment]
Hi @k82cn! 
As I can see right now that the build is passed. So, should I do something else to pass it through the Travis pipeline? :)

**Review by k82cn — APPROVED** [review]

**Pull request merged**
