### PR TITLE
Cherry-Pick #306 from Volcano

### PR DESCRIPTION
**Pull request by asifdxtreme**
https://github.com/volcano-sh/volcano/pull/306

### CODE REVIEW

**Comment by asifdxtreme** [comment]
I Signed it

**Comment by hex108** [comment]
> william-wang needs CLA

It might be the problem. cc @william-wang

**Comment by william-wang** [comment]
I just Signed the CLA.

**Comment by asifdxtreme** [comment]
I Signed it

**Comment by asifdxtreme** [comment]
I signed it

**Comment by asifdxtreme** [comment]
> I just Signed the CLA.

@william-wang Can you please try to signin again with exactly same username as github

**Comment by william-wang** [comment]
> @william-wang Can you please try to signin again with exactly same username as github
I just signed again.

**Comment by asifdxtreme** [comment]
I Signed it

**Comment by k82cn** [comment]
it is better to get this one merged this week!

**Comment by asifdxtreme** [comment]
@k82cn Does this PR needs to be a part of v0.5 release?

**Comment by k82cn** [comment]
please also cherry-pick to 0.5 release.

**Pull request merged**
