### PR TITLE
fix(helps):rm pkg/apis/helpers/helpers.go

### PR DESCRIPTION
**Pull request by leileiwan**
**Release note**:

```release-note
The helpers.go is useless for kube-batch logic
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
please remove this file from  hack/.golint_failures

**Comment by k82cn** [comment]
LGTM overall, let's get this merge when CI happy :)

**Comment by leileiwan** [comment]
hack/verify-golint.sh 执行失败
```
go get: github.com/golang/lint@v0.0.0-20191125180803-fdd1cda4f05f: parsing go.mod:
	module declares its path as: golang.org/x/lint
	        but was required as: github.com/golang/lint
```

**Comment by ingvagabund** [comment]
@leileiwan there's no need for the second `Merge pull request #1 from kubernetes-sigs/master` commit. #926 is already merged.

**Comment by ingvagabund** [comment]
https://github.com/kubernetes-sigs/kube-batch/pull/928 to address `module declares its path as: golang.org/x/lint but was required as: github.com/golang/lint` error

**Pull request merged**
