### PR TITLE
Add CheckNodeDiskPressure,CheckNodePIDPressure,CheckNodeMemoryPressur…

### PR DESCRIPTION
**Pull request by wackxu**
…e,CheckNodeCondition for kube-batch

**Special notes for your reviewer**:
@k82cn 

**Release note**:

```release-note
Add CheckNodeDiskPressure,CheckNodePIDPressure,CheckNodeMemoryPressure,CheckNodeCondition for kube-batch
```

### CODE REVIEW

**Comment by wackxu** [comment]
@hex108

**Comment by hex108** [comment]
@k82cn Need we add more predicates and add a configure for enable/disable these predicates?

**Comment by k82cn** [comment]
> Need we add more predicates and add a configure for enable/disable these predicates?

Configuration is a good idea! That's ok to add more predicates if it's useful to some users; and I agree with you to have a configuration for them.

**Comment by k82cn** [comment]
@wackxu , would you also help to open another issue about the configuration? Those predicates is not complex so no impact to the performance, but that's better to have configuration for them later as @hex108 said.

**Comment by k82cn** [comment]
@hex108 , prefer to get this PR merged, and open another issue/pr for the configuration part; WDYT?

**Comment by wackxu** [comment]
@k82cn Open issue https://github.com/kubernetes-sigs/kube-batch/issues/802. Agree with that merge the pr first and we can open other pr for configuration part.

**Comment by hex108** [comment]
> @wackxu , would you also help to open another issue about the configuration? Those predicates is not complex so no impact to the performance, but that's better to have configuration for them later as @hex108 said.

It's OK. :)

**Comment by hex108** [comment]
> @hex108 , prefer to get this PR merged, and open another issue/pr for the configuration part; WDYT?

It's OK. :)

**Pull request merged**
