### PR TITLE
Xqueuejob contrib build fix

### PR DESCRIPTION
**Pull request by dmatch01**
**What this PR does / why we need it**:
Fix the separate build for the extended queuejob in contrib 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
N/A
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by animeshsingh — APPROVED** [review]
/lgtm

**Comment by dmatch01** [comment]
@k82cn Can you let me know how the merged gets kicked off?  Do we need more than 1 reviewer approval?  Please advise.

**Comment by k82cn** [comment]
> Can you let me know how the merged gets kicked off? Do we need more than 1 reviewer approval?

It need animeshsingh@ append `/lgtm` comments here :)

**Comment by dmatch01** [comment]
> > Can you let me know how the merged gets kicked off? Do we need more than 1 reviewer approval?
> 
> It need animeshsingh@ append `/lgtm` comments here :)
@k82cn I believe animeshsingh did provide the `/lgtm` 3-4 comments earlier.  Does it look correct?

**Comment by k82cn** [comment]
add `/lgtm` as normal comments here.

**Comment by dmatch01** [comment]
@animeshsingh Can you add a new /lgtm comment again per @k82cn suggestion?

**Pull request merged**
