### PR TITLE
Add metrics support documentation

### PR DESCRIPTION
**Pull request by Jeffwan**
**What this PR does / why we need it**:
We'd like to add metrics support for kube-batch in order to better monitor it's performance. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
part of #487 

**Special notes for your reviewer**:
This is working in progress. I just list few metrics here and please have look if they make sense. Please also leave comments on additional key metrics we want to add. Code change will come soon. 

**Release note**:

```release-note
Add metrics support documentation
```

### CODE REVIEW

**Comment by k82cn** [comment]
/approve

We need this doc for performance metrics; will add lgtm label when it's ready :)

**Comment by jiaxuanzhou** [comment]
> /cc @jiaxuanzhou , please also share your comments here :)

how about adding  the metrics ：
counter of retry times of one job
scheduling latency of one task  ?

**Comment by k82cn** [comment]
I'm ok with them.

> counter of retry times of one job

If we want to log this info, we need to check whether jobs are ready in `OnSessionClose`.

**Comment by k82cn** [comment]
> I will hold doc until implementation merged in order not to bring in any unclear information.

Let's address comments and get it merged firstly; if there any changes, we can open separate PR according to our implementation :)

**Comment by Jeffwan** [comment]
> > I will hold doc until implementation merged in order not to bring in any unclear information.
> 
> Let's address comments and get it merged firstly; if there any changes, we can open separate PR according to our implementation :)

Got you. No problem. Will address comments and push revision for review.

**Comment by jiaxuanzhou** [comment]
@Jeffwan lgtm ，thanks

**Comment by k82cn** [comment]
/lgtm

Thanks for your contribution :)

**Pull request merged**
