### PR TITLE
restore kube-batch

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
restore import path to `kube-batch`

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
/hold

I will fix the ci

**Comment by TommyLike** [comment]
Failed with golint missing issue:
```
I0417 07:01:02.319] Can not find golint, install with:
I0417 07:01:02.319] go get -u github.com/golang/lint/golint
```
Instead of simply quit, need to install golint in  script.

**Pull request merged**
