### PR TITLE
fix BestEffort for overused

### PR DESCRIPTION
**Pull request by chenyangxueHDU**
quick fix ths issue: [All jobs are pending, when some jobs set resources，others not set resources.](https://github.com/kubernetes-sigs/kube-batch/issues/409)

### CODE REVIEW

**Comment by k82cn** [comment]
run `./hack/update-gofmt.sh` to correct build error :)

**Comment by k82cn** [comment]
/approve

please combine those commits into one; I'll lgtm when CI is happy.

BTW, please rebase for https://github.com/kubernetes-sigs/kube-batch/pull/419

**Comment by chenyangxueHDU** [comment]
> /approve
> 
> please combine those commits into one; I'll lgtm when CI is happy.
> 
> BTW, please rebase for #419

Done :)

**Review by k82cn — COMMENTED** [review]
/lgtm

**Pull request merged**
