### PR TITLE
[Support Job Resource] Add basic job definition

### PR DESCRIPTION
**Pull request by TommyLike**
**What this PR does / why we need it**:

For supporting job resource in kube batch

### CODE REVIEW

**Comment by TommyLike** [comment]
@k82cn  what is required for a legal header? 
https://travis-ci.org/kubernetes-sigs/kube-batch/builds/518170402#L491

**Comment by k82cn** [comment]
> what is required for a legal header?

not sure, try related update script.

**Comment by TommyLike** [comment]
@k82cn  the manually added file ```zz_generated.deepcopy.go``` should be removed from header check in script file.

**Comment by k82cn** [comment]
/lgtm

> the manually added file zz_generated.deepcopy.go should be removed from header check in script file.

good

**Pull request merged**
