### PR TITLE
Extended queuejob move to contrib

### PR DESCRIPTION
**Pull request by dmatch01**
**What this PR does / why we need it**:
Initial commit extended queue job to contrib. folder
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
n/a
**Special notes for your reviewer**:
Please merge.
**Release note**:
```release-note
Initial commit extended queue job to contrib. folder
```

### CODE REVIEW

**Comment by dmatch01** [comment]
In-progress...
/hold

**Comment by k82cn** [comment]
please also make CI happy.

**Comment by dmatch01** [comment]
Travis pass so cancelling hold

/hold cancel

**Comment by dmatch01** [comment]
> please also make CI happy.

@k82cn Done!

**Pull request merged**
