### PR TITLE
Remove maintainers

### PR DESCRIPTION
**Pull request by k82cn**
Remove inactive maintainers.

@hex108 , @animeshsingh , as there's no activities in the last three monthes, I'd like to check whether you still put effort on this project?

### CODE REVIEW

**Comment by animeshsingh** [comment]
/hold
@k82cn letme discuss with the IBM team from where the code originally came to discuss if they would like someone to be maintaining this

**Comment by k82cn** [comment]
> @k82cn letme discuss with the IBM team from where the code originally came to discuss if they would like someone to be maintaining this

For the maintainer, it's better to commit more effort on this project :)

**Comment by animeshsingh** [comment]
@k82cn yes, unfortunately sometimes maintainers flip and take a lot of ip somewhere else :-) For now, you can merge this, and I will see if I find someone else internally for long term

/hold cancel

**Comment by k82cn** [comment]
> @k82cn yes, unfortunately sometimes maintainers flip and take a lot of ip somewhere else :-) For now, you can merge this, and I will see if I find someone else internally for long term


Thanks for your understanding! If anything I can help, please let me know :)

**Pull request merged**
