### PR TITLE
Removed contrib/vendor.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Release note**:
```release-note
Removed vendors; download them on demand.
```

### CODE REVIEW

**Comment by dmatch01** [comment]
@k82cn We are still working with the contribs dir. per your recommendation.  Can you add it back so that we can push our next PR this week?

**Comment by k82cn** [comment]
> We are still working with the contribs dir. 

Is it possible to move DLaaS to your repo, e.g. FfDL? kube-batch is a batch scheduler which does not include job lifecycle management part. For example, I already moved `QueueJob` to https://github.com/hpwcloud/volcano to continue the work; you can also move your code into this repo too :)

**Comment by dmatch01** [comment]
@k82cn I will take a look per your suggestion.  In the mean time could you put back the contribs directory as we have folks starting to reference the work.

**Comment by animeshsingh** [comment]
@k82cn @dmatch01 it may make sense to keep this in contrib until we get together and discuss how to collaborate on volcano?

**Comment by k82cn** [comment]
>  it may make sense to keep this in contrib until we get together and discuss how to collaborate on volcano?

That makes sense to me, please help to open PR to revert :)
As you known, several projects/people start to use `kube-batch` as batch scheduler without DLaaS; and we did not update DLaaS for a long time, that make user confused about `kube-batch`'s scope.

**Comment by animeshsingh** [comment]
Thanks @k82cn. 
@dmatch01  please ensure a version of this running with ffdl+kube-batch combination before we get this merged. Letus sync on that

**Pull request merged**
