### PR TITLE
Add New API Group for PodGroup

### LINKED ISSUE #815: Update API GroupName
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Prefer to change `PodGroup`'s GroupName from `scheduling.incubator.k8s.io` to `scheduling.sigs.k8s.io` :)

### PR DESCRIPTION
**Pull request by thandayuthapani**
**What this PR does / why we need it:**
Addition of API GroupName for PodGroup from scheduling.incubator.k8s.io/v1apha1 to scheduling.sigs.dev/v1apha2
**Which issue(s) this PR fixes**
Fixes #815

### CODE REVIEW

**Comment by k82cn** [comment]
will you enable v1alph2 in scheduling part by this pr or other PR?

**Comment by thandayuthapani** [comment]
@k82cn  I will raise different PR to include v1alpha2 in scheduling part

**Comment by k82cn** [comment]
> I will raise different PR to include v1alpha2 in scheduling part

That's ok to me :) Thanks.

**Pull request merged**
