### PR TITLE
Added a unit test for jobOrderFn in gang plugin

### PR DESCRIPTION
**Pull request by dhzhuo**
**What this PR does / why we need it**:

This PR added a unit test for `jobOrderFn` in Gang plugin.  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by k82cn** [comment]
/approve

The CI failure is not related to this PR, I'll fix the CI in other PR.

**Comment by k82cn** [comment]
@DonghuiZhuo , please help to rebase the PR and sign LF/CLA :)

**Comment by dhzhuo** [comment]
@k82cn I have signed CLA as an individual.

**Comment by k82cn** [comment]
@DonghuiZhuo , are you still working on this PR?

**Comment by dhzhuo** [comment]
The implementation of the order function has changed. The unit test in this PR no longer apply. 

Close the PR.

**Pull request closed without merging**
