### PR TITLE
QueueJob Controller into a separate daemon.  

### PR DESCRIPTION
**Pull request by dmatch01**
Move queuejob controller into a separate daemon (issue #212).  Please note that documentation refers to a existing image `kubearbitrator/queuejob-ctrl:v0.1` in DockerHub.  `$GOPATH/deployment/Dockerfile.queuejob-ctrl` can be used to build the image: `docker build -f Dockerfile.queuejob-ctrl -t kubearbitrator/queuejob-ctrl:v0.1 .`.  Once the image is create it will need to be pushed to DockerHub.

Fixes: #212

### CODE REVIEW

**Comment by dmatch01** [comment]
Completed required forms.

**Comment by k82cn** [comment]
please sign CLA, and run `make verify` :)

**Comment by dmatch01** [comment]
It seems that the CLA/linuxfoundation form I submitted has not been processed.  Opened a ticket (https://rt.linuxfoundation.org/SelfService/Display.html?id=56078) to help resolve this problem.

**Comment by dmatch01** [comment]
Closed and resubmitted PR #219 with proper signed commit.

**Pull request closed without merging**
