### PR TITLE
Enable elder e2e tests in CI

### PR DESCRIPTION
**Pull request by TommyLike**
**What this PR does / why we need it**:
Enable elder e2e tests in Travis.

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
@TommyLike this change looks good.
The test case ```'Try to fit unassigned task with different resource requests in one loop'``` is failing due to task priority.
To pass the test case we need to swap the ```workerPriority``` with ```masterPriority```.
But i am not sure if this test was passing earlier, then there could be a bug in the kube-batch?

Why its failing:
If you see the below code the replicaset will fill the pods with onecpu across all the nodes.
And it will leave only one slot empty which is ```'one cpu core'```, then test tries to create the job with two task one with higher prirority and the other with lower priority.
But the task with higher priority cant be scheduled since it requests ```Two cpu-cores``` there is only one cpu core only left in the cluster in some node. So it blocks the other task also resulting in both of them not getting scheduled.

https://github.com/kubernetes-sigs/kube-batch/blob/5b048be1b1d15fa03e84b6ea722733b7c87205bb/test/e2e/kube-batch/job.go#L64-L95

**Comment by shivramsrivastava** [comment]
@TommyLike i will raise a pr with the fix for the test case failure.
But i need to confirm is that the actual/correct behaviour?
And if so how was this passing all this time?

**Comment by TommyLike** [comment]
@shivramsrivastava not sure, it's working on my local environment.

**Comment by shivramsrivastava** [comment]
@TommyLike it fails in my local environment ( kind cluster) consistently.

**Comment by shivramsrivastava** [comment]
```
=== RUN   TestE2E
Running Suite: volcano Test Suite
=================================
Random Seed: 1556100102
Will run 1 of 4 specs

S
------------------------------
• Failure [87.406 seconds]
Job E2E Test
/home/root1/gopathPoseidon/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/job.go:23
  Try to fit unassigned task with different resource requests in one loop [It]
  /home/root1/gopathPoseidon/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/job.go:64

  
  Cluster Info:
    Nodes:
  
      Name: shiv-control-plane
      Allocatable:
        Pods: 110
        CPU: 4
        Memory: 16297844Ki
      Conditions: 
        NetworkUnavailable=False
        MemoryPressure=False
        DiskPressure=False
        PIDPressure=False
        Ready=True
      Taints: 
        node-role.kubernetes.io/master  NoSchedule
  
      Name: shiv-worker
      Allocatable:
        Pods: 110
        CPU: 4
        Memory: 16297844Ki
      Conditions: 
        NetworkUnavailable=False
        MemoryPressure=False
        DiskPressure=False
        PIDPressure=False
        Ready=True
      Taints: 
  
      Name: shiv-worker2
      Allocatable:
        Pods: 110
        CPU: 4
        Memory: 16297844Ki
      Conditions: 
        NetworkUnavailable=False
        MemoryPressure=False
        DiskPressure=False
        PIDPressure=False
        Ready=True
      Taints: 
  
      Name: shiv-worker3
      Allocatable:
        Pods: 110
        CPU: 4
        Memory: 16297844Ki
      Conditions: 
        NetworkUnavailable=False
        MemoryPressure=False
        DiskPressure=False
        PIDPressure=False
        Ready=True
      Taints: 
  
  
    Pods:
      coredns-86c58d9df4-chr2m                     kube-system    Running   shiv-control-plane
      coredns-86c58d9df4-v59wz                     kube-system    Running   shiv-control-plane
      etcd-shiv-control-plane                      kube-system    Running   shiv-control-plane
      kube-apiserver-shiv-control-plane            kube-system    Running   shiv-control-plane
      kube-controller-manager-shiv-control-plane   kube-system    Running   shiv-control-plane
      kube-proxy-d5sjb                             kube-system    Running   shiv-worker2
      kube-proxy-kq7c8                             kube-system    Running   shiv-worker
      kube-proxy-wt27b                             kube-system    Running   shiv-worker3
      kube-proxy-xwbbl                             kube-system    Running   shiv-control-plane
      kube-scheduler-shiv-control-plane            kube-system    Running   shiv-control-plane
      weave-net-42jd4                              kube-system    Running   shiv-worker2
      weave-net-9qj7r                              kube-system    Running   shiv-worker3
      weave-net-bxglq                              kube-system    Running   shiv-control-plane
      weave-net-szl8s                              kube-system    Running   shiv-worker
      multi-task-diff-resource-job-0-c97kr         test           Pending             
      multi-task-diff-resource-job-1-q2hq6         test           Pending             
      rs-1-c2szf                                   test           Running   shiv-worker
      rs-1-g7x6d                                   test           Running   shiv-worker2
      rs-1-k7gcm                                   test           Running   shiv-worker3
      rs-1-mq8zq                                   test           Running   shiv-worker3
      rs-1-nm88z                                   test           Running   shiv-worker2
      rs-1-rkmqw                                   test           Running   shiv-worker3
      rs-1-w5sbt                                   test           Running   shiv-worker
      rs-1-wqspw                                   test           Running   shiv-worker
  
  
  Expected error:
      <*errors.errorString | 0xc00007b700>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /home/root1/gopathPoseidon/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/job.go:102
------------------------------
SS

Summarizing 1 Failure:

[Fail] Job E2E Test [It] Try to fit unassigned task with different resource requests in one loop 
/home/root1/gopathPoseidon/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/job.go:102

Ran 1 of 4 Specs in 87.406 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 3 Skipped
--- FAIL: TestE2E (87.41s)
FAIL
FAIL	github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch	87.415s
hack/run-e2e.sh: line 15: 20922 Killed                  nohup ${KA_BIN}/kube-batch --kubeconfig ${HOME}/.kube/config --scheduler-conf=config/kube-batch-conf.yaml --logtostderr --v ${LOG_LEVEL} > scheduler.log 2>&1
```

**Comment by TommyLike** [comment]
It's unstable or have deeper root cause which we can't identify for now, tested it can work with my environment:
```
Running Suite: volcano Test Suite
=================================
Random Seed: 1556160960
Will run 2 of 2 specs

this is the cluster size 12• [SLOW TEST:33.914 seconds]
Job E2E Test
/root/go_projects/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/job.go:25
  Try to fit unassigned task with different resource requests in one loop
  /root/go_projects/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/job.go:26
------------------------------
S [SKIPPING] [0.000 seconds]
Job E2E Test
/root/go_projects/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/benchmark.go:51
  [Feature:Performance] Schedule Density Job [It]
  /root/go_projects/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/benchmark.go:52

  Performance test skipped since config file not found

  /root/go_projects/src/github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch/benchmark.go:54
------------------------------

Ran 1 of 2 Specs in 33.915 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 1 Skipped
--- PASS: TestE2E (33.91s)
PASS
ok  	github.com/kubernetes-sigs/kube-batch/test/e2e/kube-batch	33.925s
```

**Comment by TommyLike** [comment]
@k82cn  your call.

**Comment by TommyLike** [comment]
This patch is not required anymore, due to the merge of #806

**Pull request closed without merging**
