### PR TITLE
Update community contact points to be SIG-Scheduling

### PR DESCRIPTION
**Pull request by coderanger**
Nice to keep SIG-specific questions out of the bigger project channels.

### CODE REVIEW

**Comment by coderanger** [comment]
Test failure looks unrelated, copyright year update issue.

**Comment by Huang-Wei** [comment]
Need @k82cn or @hzxuzhonghu to approve this. But they may be on the Chinese New Year vacation :)

**Comment by coderanger** [comment]
I don't think the tests are going to pass until someone updates the copyright year in all the generated files. I'll ping the github admins team to see if someone can override merge this since it's not something that should block on the project tests :)

**Pull request merged**
